export const chapters = [
  {
    number: 1,
    sanskrit: "Arjuna Vishada Yoga",
    title: "The Yoga of Arjuna's Grief",
    theme: " Arjuna Vishada Yoga",
    country: "India",
    description:
      "Arjuna, standing between two armies, is overcome with grief at the prospect of fighting his own kin. This chapter sets the stage for the entire Gita — the human condition of confusion, attachment, and the desperate need for divine guidance. It teaches us that the spiritual journey often begins in the darkest moment.",
    verses: 47,
    color: "from-blue-900 to-blue-800",
  },
  {
    number: 2,
    sanskrit: "Sankhya Yoga",
    title: "The Yoga of Knowledge",
    theme: "Sankhya Yoga",
    country: "United Kingdom",
    description:
      "Krishna introduces the foundational teachings of the Gita: the immortality of the soul (atman), the nature of the body, and the concept of svadharma — one's own duty. This chapter contains the essence of the entire Gita in concentrated form, including the famous description of the Sthitaprajna — the person of steady wisdom.",
    verses: 72,
    color: "from-indigo-900 to-indigo-800",
  },
  {
    number: 3,
    sanskrit: "Karma Yoga",
    title: "The Yoga of Action",
    theme: "Karma Yoga",
    country: "United States",
    description:
      "Krishna explains the path of selfless action — performing one's duties without attachment to results. This chapter introduces the concept of yajna (sacrifice) as the basis of a righteous life, and addresses the paradox of action in a world where true liberation requires transcending action.",
    verses: 43,
    color: "from-green-900 to-green-800",
  },
  {
    number: 4,
    sanskrit: "Jnana Karma Sanyasa Yoga",
    title: "The Yoga of Knowledge and Renunciation",
    theme: "Jnana Karma Sanyasa Yoga",
    country: "Australia",
    description:
      "Krishna reveals the eternal nature of his own divine incarnations and the science of knowledge as a path to liberation. He describes how wisdom destroys the boat of sin and liberates the soul, and introduces the concept of the guru-disciple relationship as the vehicle of authentic transmission.",
    verses: 42,
    color: "from-teal-900 to-teal-800",
  },
  {
    number: 5,
    sanskrit: "Karma Sanyasa Yoga",
    title: "The Yoga of Renunciation",
    theme: "Karma Sanyasa Yoga",
    country: "Canada",
    description:
      "This chapter reconciles the apparent contradiction between the path of action and the path of renunciation, showing that true renunciation is not withdrawal from the world but inner non-attachment. The liberated person acts fully in the world while remaining inwardly free and at peace.",
    verses: 29,
    color: "from-cyan-900 to-cyan-800",
  },
  {
    number: 6,
    sanskrit: "Dhyana Yoga",
    title: "The Yoga of Meditation",
    theme: "Dhyana Yoga",
    country: "Germany",
    description:
      "Krishna provides detailed guidance on the practice of meditation — the discipline of the mind, the posture, the environment, the object of meditation, and the fruits of sustained practice. This chapter is the definitive Gita teaching on yoga as a practical, embodied discipline of self-mastery.",
    verses: 47,
    color: "from-violet-900 to-violet-800",
  },
  {
    number: 7,
    sanskrit: "Jnana Vijnana Yoga",
    title: "The Yoga of Knowledge and Wisdom",
    theme: "Jnana Vijnana Yoga",
    country: "Japan",
    description:
      "Krishna reveals the nature of his divine manifestation — the eight-fold material nature and the higher spiritual nature. He explains the four types of devotees who approach him and the nature of maya (divine illusion) that veils the true nature of reality. Knowledge here transcends information — it is direct experience of the divine.",
    verses: 30,
    color: "from-purple-900 to-purple-800",
  },
  {
    number: 8,
    sanskrit: "Akshara Brahma Yoga",
    title: "The Yoga of the Imperishable Brahman",
    theme: "Akshara Brahma Yoga",
    country: "Brazil",
    description:
      "This chapter addresses the profound questions of death, the afterlife, and liberation. Krishna explains the significance of the final thought at the moment of death, the nature of the cosmic day and night of Brahma, and the path to the imperishable Brahman. 'Remember me at the moment of death and you will come to me.'",
    verses: 28,
    color: "from-rose-900 to-rose-800",
  },
  {
    number: 9,
    sanskrit: "Raja Vidya Raja Guhya Yoga",
    title: "The Yoga of Royal Knowledge and Royal Secret",
    theme: "Raja Vidya Raja Guhya Yoga",
    country: "South Africa",
    description:
      "Krishna reveals the 'most secret of secrets' — the nature of his all-pervading divine presence and the power of pure, unconditional devotion. This chapter contains one of the most beloved promises in all of scripture: 'Fix your mind on Me, be devoted to Me, worship Me, bow down to Me — so shall you come to Me.'",
    verses: 34,
    color: "from-orange-900 to-orange-800",
  },
  {
    number: 10,
    sanskrit: "Vibhuti Yoga",
    title: "The Yoga of Divine Glories",
    theme: "Vibhuti Yoga",
    country: "France",
    description:
      "Krishna describes his divine manifestations in the world — 'I am the self seated in the heart of all beings, I am the beginning, middle, and end of all created things.' This chapter is a cosmic hymn to the divine presence that pervades and sustains all of existence.",
    verses: 42,
    color: "from-yellow-900 to-yellow-800",
  },
  {
    number: 11,
    sanskrit: "Vishwarupa Darshana Yoga",
    title: "The Yoga of the Vision of the Cosmic Form",
    theme: "Vishwarupa Darshana Yoga",
    country: "Russia",
    description:
      "The most dramatic chapter of the Gita — Arjuna is granted the vision of Krishna's universal cosmic form (Vishwarupa), encompassing all of time and creation. Arjuna is overwhelmed with wonder and terror. This is the Gita's most spectacular theophany — a direct encounter with the infinite.",
    verses: 55,
    color: "from-amber-900 to-amber-800",
  },
  {
    number: 12,
    sanskrit: "Bhakti Yoga",
    title: "The Yoga of Devotion",
    theme: "Bhakti Yoga",
    country: "Singapore",
    description:
      "The shortest and perhaps the most beloved chapter of the Gita — a direct dialogue on the nature of pure devotion. Krishna defines the qualities of the ideal devotee: free from hatred, friendly and compassionate, equal in all circumstances, content, steady in conviction, with mind and intellect fixed on the divine.",
    verses: 20,
    color: "from-pink-900 to-pink-800",
  },
  {
    number: 13,
    sanskrit: "Kshetra Kshetrajna Vibhaga Yoga",
    title: "The Yoga of Field and Knower of the Field",
    theme: "Kshetra Kshetrajna Vibhaga Yoga",
    country: "Israel",
    description:
      "A profound philosophical chapter distinguishing between the body (the field) and the soul (the knower of the field). Krishna explains the twenty-four elements of material nature, the qualities of true knowledge, and the nature of the supreme Brahman that pervades and transcends all of creation.",
    verses: 35,
    color: "from-lime-900 to-lime-800",
  },
  {
    number: 14,
    sanskrit: "Gunatraya Vibhaga Yoga",
    title: "The Yoga of the Three Modes of Nature",
    theme: "Gunatraya Vibhaga Yoga",
    country: "New Zealand",
    description:
      "Krishna explains the three fundamental modes (gunas) of material nature — tamas (inertia), rajas (passion), and sattva (clarity) — and how they condition all beings. The path to liberation lies in transcending all three modes and reaching the state of trigunatita — beyond the gunas.",
    verses: 27,
    color: "from-emerald-900 to-emerald-800",
  },
  {
    number: 15,
    sanskrit: "Purushottama Yoga",
    title: "The Yoga of the Supreme Person",
    theme: "Purushottama Yoga",
    country: "UAE",
    description:
      "One of the most poetic chapters — beginning with the image of the upside-down Ashvattha tree (the cosmic tree of existence) whose roots are above and branches below. Krishna describes the nature of the Supreme Person (Purushottama) who transcends both the perishable and the imperishable aspects of existence.",
    verses: 20,
    color: "from-sky-900 to-sky-800",
  },
  {
    number: 16,
    sanskrit: "Daivasura Sampad Vibhaga Yoga",
    title: "The Yoga of Divine and Demoniac Natures",
    theme: "Daivasura Sampad Vibhaga Yoga",
    country: "Kenya",
    description:
      "Krishna enumerates the qualities that lead to liberation (the divine heritage) and those that lead to bondage (the demoniac heritage). This chapter is a psychological and ethical map — a clear description of the qualities of the evolved soul and the qualities that obstruct spiritual growth.",
    verses: 24,
    color: "from-stone-800 to-stone-700",
  },
  {
    number: 17,
    sanskrit: "Shraddhatraya Vibhaga Yoga",
    title: "The Yoga of the Three Divisions of Faith",
    theme: "Shraddhatraya Vibhaga Yoga",
    country: "Argentina",
    description:
      "An exploration of the three modes of faith and how they shape our food, sacrifice, austerity, and charity. This chapter reveals that even our most ordinary daily choices are expressions of our inner orientation — and that true spiritual practice is a transformation of every dimension of life.",
    verses: 28,
    color: "from-zinc-800 to-zinc-700",
  },
  {
    number: 18,
    sanskrit: "Moksha Sanyasa Yoga",
    title: "The Yoga of Liberation Through Renunciation",
    theme: "Moksha Sanyasa Yoga",
    country: "India",
    description:
      "The final and longest chapter — a summary and culmination of all the Gita's teachings. Krishna defines true renunciation, reviews all the yogas, and delivers the supreme teaching: 'Abandon all varieties of religion and simply surrender unto Me. I shall liberate you from all sinful reactions; do not fear.' Arjuna's confusion is dissolved and the Gita concludes.",
    verses: 78,
    color: "from-gold-dark to-gold",
  },
];
