export type Country = {
  id: number;
  name: string;
  slug: string;
  language: string;
  description: string;
  gallery: string[];
  videos: string[];
};

export const countries: Country[] = [
  {
    id: 1,
    name: "India",
    slug: "india",
    language: "Hindi, English",
    description: "The central home of the Bhagavad Gita Vishwa Mahotsav journey, bringing together the chapters, languages and communities of the Vishwa Mahotsav.",
    gallery: [],
    videos: [],
  },
  {
    id: 2,
    name: "USA",
    slug: "usa",
    language: "English",
    description: "A participating nation in the global Gita journey, connecting communities through the wisdom, recitation and cultural expression of the Bhagavad Gita.",
    gallery: [],
    videos: [],
  },
  {
    id: 3,
    name: "Canada",
    slug: "canada",
    language: "English, French",
    description: "A global chapter of the Bhagavad Gita Vishwa Mahotsav journey, bringing communities together through recitation, reflection and cultural exchange.",
    gallery: [],
    videos: [],
  },
  {
    id: 4,
    name: "Brazil",
    slug: "brazil",
    language: "Portuguese",
    description: "A participating nation in the global Gita journey, connecting a diverse community through the universal message of the Bhagavad Gita.",
    gallery: [],
    videos: [],
  },
  {
    id: 5,
    name: "South Africa",
    slug: "south-africa",
    language: "English, Afrikaans, Zulu, Xhosa and more",
    description: "A participating nation in the global Gita journey, bringing communities together through recitation and the timeless teachings of the Bhagavad Gita.",
    gallery: [],
    videos: [],
  },
  {
    id: 6,
    name: "United Kingdom",
    slug: "united-kingdom",
    language: "English",
    description: "A participating nation in the global Gita journey, creating opportunities for recitation, learning and cultural connection.",
    gallery: [],
    videos: [],
  },
  {
    id: 7,
    name: "Ireland",
    slug: "ireland",
    language: "English, Irish",
    description: "A participating nation in the global Gita journey, celebrating shared wisdom and cultural participation.",
    gallery: [],
    videos: [],
  },
  {
    id: 8,
    name: "France",
    slug: "france",
    language: "French",
    description: "A participating nation in the global Gita journey, celebrating wisdom, recitation and cultural exchange.",
    gallery: [],
    videos: [],
  },
  {
    id: 9,
    name: "Germany",
    slug: "germany",
    language: "German",
    description: "A participating nation in the global Gita journey, connecting people through the universal teachings of the Bhagavad Gita.",
    gallery: [],
    videos: [],
  },
  {
    id: 10,
    name: "Italy",
    slug: "italy",
    language: "Italian",
    description: "A participating nation in the global Gita journey, bringing together reflection, recitation and cultural appreciation.",
    gallery: [],
    videos: [],
  },
  {
    id: 11,
    name: "Spain",
    slug: "spain",
    language: "Spanish",
    description: "A participating nation in the global Gita journey, celebrating the Bhagavad Gita through recitation, learning and community participation.",
    gallery: [],
    videos: [],
  },
  {
    id: 12,
    name: "Netherlands",
    slug: "netherlands",
    language: "Dutch",
    description: "A participating nation in the global Gita journey, bringing the timeless teachings of the Bhagavad Gita to local communities.",
    gallery: [],
    videos: [],
  },
  {
    id: 13,
    name: "Russia",
    slug: "russia",
    language: "Russian",
    description: "Representing Russia in the global Gita journey, sharing the timeless wisdom of the Bhagavad Gita.",
    gallery: [],
    videos: [],
  },
  {
    id: 14,
    name: "China",
    slug: "china",
    language: "Chinese (Mandarin)",
    description: "A participating nation in the global Gita journey, creating a bridge between ancient wisdom and a global audience.",
    gallery: [],
    videos: [],
  },
  {
    id: 15,
    name: "Japan",
    slug: "japan",
    language: "Japanese, English",
    description: "A participating nation in the global Gita journey, bringing together reflection, recitation and cultural appreciation.",
    gallery: [],
    videos: [],
  },
  {
    id: 16,
    name: "UAE",
    slug: "uae",
    language: "Arabic, English",
    description: "A participating nation in the global Gita journey, connecting communities through the universal wisdom of the Bhagavad Gita.",
    gallery: [],
    videos: [],
  },
  {
    id: 17,
    name: "Australia",
    slug: "australia",
    language: "English",
    description: "A participating nation in the global Gita journey, sharing the timeless wisdom of the Bhagavad Gita across cultures and communities.",
    gallery: [],
    videos: [],
  },
  {
    id: 18,
    name: "New Zealand",
    slug: "new-zealand",
    language: "English, Māori",
    description: "A participating nation in the global Gita journey, sharing the universal message of the Bhagavad Gita with communities across the country.",
    gallery: [],
    videos: [],
  },
];
